$ANSIBLE_VAULT;1.1;AES256
31363436383831343039643831666635633861313838363030353265303639613632316338303263
6530636436393331613364333337656437633030303330320a376134313034333736393466666336
30336463326134343130623965373664343763613861386262353863643335396163663635396563
6334383937633238300a343766636536653831646336326137333464353161343364653432653138
31326661383434313738666337353262326161343063653333663237313634613535623830383031
3866326539356164643839383162343964346535313134336364
