$ANSIBLE_VAULT;1.1;AES256
38393065653164393232313137613034653464646133306639613139663262383665643263363365
6432646439383435373234313733656265613065373330630a393035633634633532616636356334
37386362623133353436323734626164373731343939633332356133393730333765333661303263
6162666533643962350a626135326439303838353031313835656139636438633632396363393961
65343135373334376232393230383266386535383836313437383133656639636537
