$ANSIBLE_VAULT;1.1;AES256
62326437373234643430376539366332336364616434383838623033643132633634663266363434
6164363065393064343039386565636164333663303665310a323033353063663531376637353531
31396365366536636565303339633962316335373132323239666233346633633739353830333864
6433636435626334640a323730373063313734356533323732313431306565626463653738396566
39633635643361623037616330393065383039303431303134326338303832363663313335336434
3863636231316466613734343130613732653937383834363331
