# ansible/group_vars/all.yml
vmid:
    traefik: 200
    servarr: 201
    adguard: 202
    monitoring: 204
    identity: 205
    master: 300
    worker-1: 301
    worker-2: 302
    # jenkins: 203
default_start_dir: "/opt/homelab-stack/docker-compose"
min_user_id: 1000
