$ANSIBLE_VAULT;1.1;AES256
30616634336635646634643330396361383234393935313865336166353132626437656564363133
6234643033663534643461633737636332303161383339310a303863663436333566366434613932
37346132333534376166646232386333636138653031393466353231646332353739356661623237
3933353465326464650a356137643733363830616534303535353764356438306334383432346230
35333837383239363035313363303835373032383330356565373130616365626165353230366361
38386562363664653261376461646536373633643462343066643862646262313231383135623136
63316433396436356262313432386666636563396239323363346161623435646433666436396132
38303536363134373439336332393632363064336438393561626130613664356236336436316539
64393332653364316636653934383066306433613236313139393137353330316636663966363437
34666661316233303965663630656535336631336266623037353537343838306364303333316239
66663033386466633163396262363661346233646461613165666136316438313930383862303833
30323138386164366465623361663664633265656134363636633466343434323634393634333235
3537
