$ANSIBLE_VAULT;1.1;AES256
38653935333834303163333433313763653634633334376363653830333639663561633738656564
6662616361656265663563346537393530353334373932360a646530313430663631323463353830
32353563393965623834666130333030303761373366396334366464313533376338396136306236
3838623262346362300a393265343837373339303665626636316235313037303234343561353734
64346164396333643932383236353666616537643264663232653134303165306564663832613266
32303132363366316436653739393366343530626362653535313861343834323430333561343435
66363062306434646535616634343133363661626630383563333533396636396238623634346663
30663934653466303734633438613337323937626530303966616431633131373232366235393134
37656235623731613231393865376433643031656332303834393836373730343633336434623662
65656237663963393932383237376236323866313733313431663030333163313763303834663865
33386466663336386233353063383532623430396639663035633936336536656134633465313166
61623236336535323836353736643838303639666331666365313031656163643835313039386638
3439
