$ANSIBLE_VAULT;1.1;AES256
32336531323965663836333362366234346233396361626436646631656436663762666563326639
3065353462663262666130636466316361653335316538340a366664363664343432346432383939
38363461323464383465323366666462383361303732653763623531323831666234666230363338
6264383138313039390a366135376334333337663732326138663738616137633634666163626361
61666131363338353638386162363661643764346364346165346362343632326362326461393966
38323933383462386634643361646264323539363865306438313333313836383464623864353538
33303662663739626363646633303761633663336365663934646433303338653339326335653836
30653335653030613338356638366265396337636637323336323762663566653464653763363436
3931
