$ANSIBLE_VAULT;1.1;AES256
38643438313934666531376330633538373361396133366562336637393064383734633261326266
6336333935346563353539323561313537353732393039610a663630386536636435376638613637
38393236313131386639386632316564653565303866383835313333323630353032323736626633
3262376333666638320a316535363566346330313339333363616661653563306631303965636462
34346532393366313636636261626331663533633033363233613761376161323035666333343665
39333861623231643761363331633634343363663964366538393764643634393837613330616539
37623934356533363039343865373662323736356531343030653035643230653438303164326636
37303061333864336163356134333839613263666338643830633265333536613233613635383339
62653438383163363362323634633038663139636236613462666265613739386262396434326163
64393633316361373266376134346431666433646539633338323131376538623536626534326262
38346466333335663030636563623234643233336266656130376536326639396332626466333231
62306134653861306566396434333534326261396231386638386130303662663831326561353366
3365
