$ANSIBLE_VAULT;1.1;AES256
66613866333530396137343139363066333937343565366131316136346134313739393332383535
3632383235336330636464323266326638363961336338390a636365336566386436346236303530
32396231653762633765653836366139383266636433646539316161643037626365303031646333
3737613438633362620a663664373039653135366537326565633632316632636563323938396364
63396238366430363033333533323866373366616566646463616362646665363238333639376235
35366466346265386366333965343965366566343038613862663937646633333633393662316635
33333362396138623039386134633764353432313731383038326330663738623764396136363761
33386230393264633139343037386330643465343036653362643165623232353361376363313234
37376330633262373833363266373035323365323937376461643634613235633939353663623634
39366533646133366231633962363133356164383434613834626330323535626335633235373066
353333376335353733613064656164663337
