$ANSIBLE_VAULT;1.1;AES256
65393739626663636631353831653534323861656537366666376538323531326339373536383136
6662306664643863626464666234653134656162643761620a623735336339373861326136343939
36646132643731393563353764323336383639333338373237356564663630626634323931343066
3463366566643266620a326135326137346430363132356232333335343430333632383737316462
35616535366534383762386633663931386534303465313230656361376365343033626439366463
62373636303033356634636139373738376439373463663465306566383937383565623638653266
63326434373838373839623531623032623630353363633264363430623532373433386162376336
35323838313330643336636164653864366565643764653861613061383934373634363066653563
31653431636433356136623666323534613265623631623133366633313833323233626438613464
39393964396139323136323363346635643665663436396163383365333139323263303130323937
37343461633535373135373765323534633866376564303464373730323432653862633962343038
34636138346662636637613265643935343630366432376265613837343438316237333962636265
32373964306632313230633734643438636536623535646239323562613139316631
