- name: Play 1 - Mettre à jour les serveurs LXC
  hosts: lxc_servers
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Tâche 1 - Rafraîchir le cache des paquets
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Tâche 2 - Mettre à jour tous les paquets
      apt:
        upgrade: yes
        autoremove: yes
