global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Surveillance du système (CPU/RAM global du LXC)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Cadvisor (Commenté pour l'instant car instable en LXC Unprivileged)
  # - job_name: 'docker-containers'
  #   static_configs:
  #     - targets: ['cadvisor:8080']